apiVersion: v2
name: istio-gateway
description: istio
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: gateway
    version: 1.28.1
    repository: https://istio-release.storage.googleapis.com/charts
