apiVersion: v2
name: cluster-autoscaler
description: cluster-autoscaler
version: 9.54.0
appVersion: "9.54.0"

dependencies:
  - name: cluster-autoscaler
    version: 9.54.0
    repository: https://kubernetes.github.io/autoscaler
