apiVersion: v2
name: cluster-autoscaler
description: cluster-autoscaler
version: 9.50.1
appVersion: "9.50.1"

dependencies:
  - name: cluster-autoscaler
    version: 9.52.1
    repository: https://kubernetes.github.io/autoscaler
