spec:
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: grafana
    jsonPointers:
    - /data/admin-password
  - jsonPointers:
    - '/spec/template/metadata/annotations/checksum~1secret'
    name: grafana
    kind: Deployment
    group: apps
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        tenancy.entigo.com/zone: infralib
