apiVersion: v2
name: prometheus
description: A Prometheus chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: prometheus
    version: 28.9.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-operator-crds
    version: 27.0.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: global.installPrometheusOperatorCRDs
  - name: prometheus-blackbox-exporter
    version: 11.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: global.installBlackbox
