apiVersion: v2
name: wireguard
description: A Wireguard chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: wireguard
  version: 0.31.0
  repository: https://bryopsida.github.io/wireguard-chart
