{{- if eq .Values.global.cloudProvider "google" }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-gke-metadata
  namespace: {{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # GKE Dataplane V1
    - to:
        - ipBlock:
            cidr: 169.254.169.252/32
      ports:
        - protocol: TCP
          port: 988
    # GKE Dataplane V2
    - to:
        - ipBlock:
            cidr: 169.254.169.254/32
      ports:
        - protocol: TCP
          port: 80

{{- end }}
