kyverno:
  global:
    image:
      registry: ghcr.io

  features:
    generateValidatingAdmissionPolicy:
      enabled: false
    generateMutatingAdmissionPolicy:
      enabled: false
    logging:
      format: json
      verbosity: 2
    reporting:
      # -- Enables the feature
      validate: false
      # -- Enables the feature
      mutate: false
      # -- Enables the feature
      mutateExisting: false
      # -- Enables the feature
      imageVerify: false
      # -- Enables the feature
      generate: false
  crds:
    annotations:
      argocd.argoproj.io/sync-wave: "-1"
    migration:
      podAnnotations:
        kube-score/ignore: pod-networkpolicy
      podResources:
        limits:
          memory: 256Mi
          cpu: 1000m
          ephemeral-storage: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
          ephemeral-storage: 24Mi
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 90
            preference:
              matchExpressions:
                - key: tools
                  operator: In
                  values:
                    - "true"
      tolerations:
        - key: "tools"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
  admissionController:
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    initContainer:
      resources:
        limits:
          memory: 256Mi
          cpu: 100m
          ephemeral-storage: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
          ephemeral-storage: 24Mi
    container:
      resources:
        limits:
          memory: 1Gi
          cpu: 1000m
          ephemeral-storage: 1Gi
        requests:
          cpu: 60m
          memory: 192Mi
          ephemeral-storage: 24Mi
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    networkPolicy:
      enabled: true
  backgroundController:
    enabled: true
    podAnnotations:
      kube-score/ignore: pod-probes
    resources:
      limits:
        memory: 1Gi
        cpu: 1000m
        ephemeral-storage: 1Gi
      requests:
        cpu: 20m
        memory: 128Mi
        ephemeral-storage: 24Mi
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    networkPolicy:
      enabled: true
  cleanupController:
    enabled: false
    resources:
      limits:
        memory: 128Mi
        cpu: 1000m
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 24Mi
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    networkPolicy:
      enabled: true
  reportsController:
    enabled: false
    podAnnotations:
      kube-score/ignore: pod-probes
    resources:
      limits:
        memory: 128Mi
        cpu: 1000m
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 24Mi
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 90
          preference:
            matchExpressions:
              - key: tools
                operator: In
                values:
                  - "true"
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
    networkPolicy:
      enabled: true

  webhooksCleanup:
    podAnnotations:
      kube-score/ignore: pod-probes,pod-networkpolicy
    resources:
      limits:
        memory: 256Mi
        cpu: 1000m
        ephemeral-storage: 1Gi
      requests:
        cpu: 10m
        memory: 64Mi
        ephemeral-storage: 24Mi
    tolerations:
      - key: "tools"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
