global:
  cloudProvider: aws
  providerConfigRefName: crossplane-aws
  serviceAccount: contrib-provider-kafka
  aws:
    account: ""
    clusterOIDC: ""
    assumeRole: ""
    crossplaneSystemNamespace: ""