global:
  aws:
    role: "{{ .toutput.crossplane.iam_role }}"
    region: "{{ .toutput.eks.region }}"
    vpc:
      name: "{{ .toutput.vpc.name }}"
      id: "{{ .toutput.vpc.vpc_id }}"
      database_subnets_id: |
        {{ .toptout.vpc.database_subnets }}
      elasticache_subnets_id: |
        {{ .toptout.vpc.elasticache_subnets }}
      compute_subnets_id: |
        {{ .toptout.vpc.compute_subnets }}
      database_subnet_group_name: "{{ .toptout.vpc.database_subnet_group_name }}"
      elasticache_subnet_group_name: "{{ .toptout.vpc.elasticache_subnet_group_name }}"
    kms:
      data_key_arn: "{{ .toptout.kms.data_key_arn }}"
      data_alias_arn: "{{ .toptout.kms.data_alias_arn }}"
      config_key_arn: "{{ .toptout.kms.config_key_arn }}"
      config_alias_arn: "{{ .toptout.kms.config_alias_arn }}"
      telemetry_key_arn: "{{ .toptout.kms.telemetry_key_arn }}"
      telemetry_alias_arn: "{{ .toptout.kms.telemetry_alias_arn }}"
    eks:
      cluster_name: "{{ .toutput.eks.cluster_name }}"
      node_security_group_id: "{{ .toutput.eks.node_security_group_id }}"
      cluster_primary_security_group_id: "{{ .toutput.eks.cluster_primary_security_group_id }}"
    ecrProxy:
      policy: "{{ .toptout.ecr-proxy.policy }}"
