installProviderConfig: true

global:
  extraProviders: []
  observerProviders: ["ecr", "rds", "kms", "secretsmanager", "ec2", "eks", "elasticache"]
  requiredProviders:  ["iam", "s3", "sqs"]
  createObservers: false
  createNamespacedObservers: false


  cloudProvider: ""
  aws:
    role: ""
  deploymentRuntimeConfig:
    args:
      - --enable-management-policies
