apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{.Values.logs.controller.priorityClassName}}
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class will cause other pods to be preempted since Logging is important."
