apiVersion: v2
name: entigo-portal-agent
description: A entigo-portal-agent chart for Kubernetes
type: application
version: 0.2.17
appVersion: "0.2.1"


dependencies:
- name: developer-portal-agent
  version: 0.2.17
  repository: oci://ghcr.io/entigolabs
