crossplane:
  image:
    repository: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}/crossplane/crossplane'
  
job:
  image: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}/entigolabs/entigo-infralib-kubectl'

imageConfigs:
  hubProxy: '{{ .toptout.gar-proxy.hub_registry | "docker.io" }}/entigolabs'
  ghcrProxy: '{{ .toptout.gar-proxy.ghcr_registry | "ghcr.io" }}/entigolabs'
