apiVersion: v2
name: crossplane
description: Crossplane operator chart
type: application
version: 2.1.3
appVersion: "2.0"

dependencies:
  - name: crossplane
    version: 2.1.3
    repository: https://charts.crossplane.io/stable
