spec:
  ignoreDifferences:
  - jsonPointers:
    - /data/config.yaml
    kind: ConfigMap
  - jsonPointers:
    - '/spec/template/metadata/annotations/checksum~1config'
    kind: Deployment
    group: apps
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: baseline
        pod-security.kubernetes.io/warn: baseline
