spec:
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: loki-read
    jqPathExpressions:
      - .spec.persistentVolumeClaimRetentionPolicy
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        tenancy.entigo.com/zone: infralib
