platform-apis:
  zone:
    kyvernoNamespace: "{{ .tmodule.kyverno }}"
    environmentConfig:
      argoCDNamespace: "{{ .tmodule.argocd }}"
  database:
    environmentConfig:
      esClusterSecretStore: "{{ .tmodule.external-secrets }}"
