apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.315

appVersion: "0.1.315"

dependencies:
  - name: platform-apis
    version: 0.1.315
    repository: oci://ghcr.io/entigolabs
