apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.253

appVersion: "0.1.253"

dependencies:
  - name: platform-apis
    version: 0.1.253
    repository: oci://ghcr.io/entigolabs

