apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.273

appVersion: "0.1.273"

dependencies:
  - name: platform-apis
    version: 0.1.273
    repository: oci://ghcr.io/entigolabs
