apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.256

appVersion: "0.1.256"

dependencies:
  - name: platform-apis
    version: 0.1.256
    repository: oci://ghcr.io/entigolabs

