apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.320

appVersion: "0.1.320"

dependencies:
  - name: platform-apis
    version: 0.1.320
    repository: oci://ghcr.io/entigolabs
