apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.255

appVersion: "0.1.255"

dependencies:
  - name: platform-apis
    version: 0.1.255
    repository: oci://ghcr.io/entigolabs

