apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.307

appVersion: "0.1.307"

dependencies:
  - name: platform-apis
    version: 0.1.307
    repository: oci://ghcr.io/entigolabs
