apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.282

appVersion: "0.1.282"

dependencies:
  - name: platform-apis
    version: 0.1.282
    repository: oci://ghcr.io/entigolabs
