apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.274

appVersion: "0.1.274"

dependencies:
  - name: platform-apis
    version: 0.1.274
    repository: oci://ghcr.io/entigolabs
