apiVersion: v2
name: platform-apis
description: Platform APIs

version: 0.1.219

appVersion: "0.1.219"

dependencies:
  - name: platform-apis
    version: 0.1.219
    repository: oci://ghcr.io/entigolabs
