global:
  aws:
    region: "{{ .toutput.eks.region }}"
    account: "{{ .toutput.eks.account }}"
    clusterOIDC: "{{ .toutput.eks.oidc_provider }}"
    createECRNamespace: "{{ .tmodule.argocd }}"
    createECRAccounts: 
    - accountNumber: "{{ .toutput.eks.account }}"
      accountRegion: "{{ .toutput.eks.region }}"
external-secrets:
  image:
    repository: '{{ .toptout.ecr-proxy.ghcr_registry | "ghcr.io" }}/external-secrets/external-secrets'
  webhook:
    image:
      repository: '{{ .toptout.ecr-proxy.ghcr_registry | "ghcr.io" }}/external-secrets/external-secrets'
  certController:
    image:
      repository: '{{ .toptout.ecr-proxy.ghcr_registry | "ghcr.io" }}/external-secrets/external-secrets'
