installProviderConfig: true

global:
  google:
    projectID: ""

  deploymentRuntimeConfig:
    googleServiceAccount: ""
    args:
      - --enable-management-policies

  extraProviders: []
  observerProviders: []
  requiredProviders: ["cloudplatform", "storage", "secretmanager"]
  createObservers: false
  createNamespacedObservers: false
